

#ifndef __GMS_CDF_PDF_AVX512_H__
#define __GMS_CDF_PDF_AVX512_H__ 290520221332



 const unsigned int GMS_PDF_CDF_AVX512_MAJOR = 1U;
 const unsigned int GMS_PDF_CDF_AVX512_MINOR = 0U;
 const unsigned int GMS_PDF_CDF_AVX512_MICRO = 0U;
 const unsigned int GMS_PDF_CDF_AVX512_FULLVER =
  1000U*GMS_PDF_CDF_AVX512_MAJOR+100U*GMS_PDF_CDF_AVX512_MINOR+10U*GMS_PDF_CDF_AVX512_MICRO;
 const char * const GMS_PDF_CDF_AVX512_CREATION_DATE = "29-05-2022 13:32 +00200 (SUN 29 MAY 2022 13:32 GMT+2)";
 const char * const GMS_PDF_CDF_AVX512_BUILD_DATE    = __DATE__ " " __TIME__ ;
 const char * const GMS_PDF_CDF_AVX512_AUTHOR        = "Programmer: Bernard Gingold, contact: beniekg@gmail.com";
 const char * const GMS_PDF_CDF_AVX512_SYNOPSIS      = "Manually vectorized [AVX512] PDF,CDF functions"


#include <immintrin.h>


/*
      !*****************************************************************************80
!
!! GAMMA_LOG calculates the natural logarithm of GAMMA ( X ).
!
!  Discussion:
!
!    Computation is based on an algorithm outlined in references 1 and 2.
!    The program uses rational functions that theoretically approximate
!    LOG(GAMMA(X)) to at least 18 significant decimal digits.  The
!    approximation for 12 < X is from Hart et al, while approximations
!    for X < 12.0D+00 are similar to those in Cody and Hillstrom,
!    but are unpublished.
!
!    The accuracy achieved depends on the arithmetic system, the compiler,
!    intrinsic functions, and proper selection of the machine dependent
!    constants.
!
!  Licensing:
!
!    This code is distributed under the GNU LGPL license.
!
!  Modified:
!
!    16 June 1999
!
!  Author:
!
!    Original FORTRAN77 version by William Cody, Laura Stoltz.
!    FORTRAN90 version by John Burkardt.
!
!  Reference:
!
!    William Cody, Kenneth Hillstrom,
!    Chebyshev Approximations for the Natural Logarithm of the Gamma Function,
!    Mathematics of Computation,
!    Volume 21, 1967, pages 198-203.
!
!    Kenneth Hillstrom,
!    ANL/AMD Program ANLC366S, DGAMMA/DLGAMA,
!    May 1969.
!
!    John Hart, Ward Cheney, Charles Lawson, Hans Maehly,
!    Charles Mesztenyi, John Rice, Henry Thacher, Christoph Witzgall,
!    Computer Approximations,
!    Wiley, 1968.
!
!  Parameters:
!
!    Input, real ( kind = 8 ) X, the argument of the Gamma function.
!    X must be positive.
!
!    Output, real ( kind = 8 ) GAMMA_LOG, the logarithm of the Gamma
!    function of X.
!
!  Local Parameters:
!
!    Local, real ( kind = 8 ) BETA, the radix for the floating-point
!    representation.
!
!    Local, integer MAXEXP, the smallest positive power of BETA that overflows.
!
!    Local, real ( kind = 8 ) XBIG, the largest argument for which
!    LN(GAMMA(X)) is representable in the machine, the solution to the equation
!      LN(GAMMA(XBIG)) = BETA**MAXEXP.
!
!    Local, real ( kind = 8 ) FRTBIG, a rough estimate of the fourth root
!    of XBIG.
!
!  Approximate values for some important machines are:
!
!                            BETA      MAXEXP         XBIG     FRTBIG
!
!  CRAY-1        (S.P.)        2        8191       9.62D+2461  3.13D+615
!  Cyber 180/855 (S.P.)        2        1070       1.72D+319   6.44D+79
!  IEEE (IBM/XT) (S.P.)        2         128       4.08D+36    1.42D+9
!  IEEE (IBM/XT) (D.P.)        2        1024       2.55D+305   2.25D+76
!  IBM 3033      (D.P.)       16          63       4.29D+73    2.56D+18
!  VAX D-Format  (D.P.)        2         127       2.05D+36    1.20D+9
!  VAX G-Format  (D.P.)        2        1023       1.28D+305   1.89D+76
!    
*/


              __m512d
	      gamma_log_zmm8r8(const __m512d) __attribute__((noinline))
			                      __attribute__((hot))
				              __attribute__((regcall))
				              __attribute__((aligned(32)));


	     
              __m512
	      gamma_log_zmm16r4(const __m512) __attribute__((noinline))
			                      __attribute__((hot))
				              __attribute__((regcall))
				              __attribute__((aligned(32)));


/*
 !*****************************************************************************80
!
!! BESSEL_I0 evaluates the modified Bessel function I0(X).
!
!  Discussion:
!
!    The main computation evaluates slightly modified forms of
!    minimax approximations generated by Blair and Edwards, Chalk
!    River (Atomic Energy of Canada Limited) Report AECL-4928,
!    October, 1974.  This transportable program is patterned after
!    the machine dependent FUNPACK packet NATSI0, but cannot match
!    that version for efficiency or accuracy.  This version uses
!    rational functions that theoretically approximate I-SUB-0(X)
!    to at least 18 significant decimal digits.
!
!  Machine dependent constants:
!
!    beta   = Radix for the floating-point system
!    maxexp = Smallest power of beta that overflows
!    XMAX =   Largest argument acceptable to BESI0;  Solution to
!             equation:
!               W(X) * (1+1/(8*X)+9/(128*X^2) = beta^maxexp
!             where  W(X) = EXP(X)/sqrt(2*PI*X)
!
!    Approximate values for some important machines are:
!
!                             beta       maxexp       XMAX
!
!    CRAY-1        (S.P.)       2         8191       5682.810
!    Cyber 180/855
!      under NOS   (S.P.)       2         1070        745.893
!    IEEE (IBM/XT,
!      SUN, etc.)  (S.P.)       2          128         91.900
!    IEEE (IBM/XT,
!      SUN, etc.)  (D.P.)       2         1024        713.986
!    IBM 3033      (D.P.)      16           63        178.182
!    VAX           (S.P.)       2          127         91.203
!    VAX D-Format  (D.P.)       2          127         91.203
!    VAX G-Format  (D.P.)       2         1023        713.293
!
!  Licensing:
!
!    This code is distributed under the GNU LGPL license.
!
!  Modified:
!
!    17 October 2008
!
!  Author:
!
!    Original FORTRAN77 version by William Cody, Laura Stoltz.
!    FORTRAN90 version by John Burkardt.
!
!  Parameters:
!
!    Input, real ( kind = 8 ) ARG, the argument.
!
!    Output, real ( kind = 8 ) BESSEL_I0, the value of the modified
!    Bessel function of the first kind.
!
*/


              
              __m512d
	      bessesl_i0_zmm8r8(const __m512d) __attribute__((noinline))
			                       __attribute__((hot))
				               __attribute__((regcall))
				               __attribute__((aligned(32)));


	       __m512
	      bessesl_i0_zmm16r4(const __m512) __attribute__((noinline))
			                       __attribute__((hot))
				               __attribute__((regcall))
				               __attribute__((aligned(32)));


/*
 !*****************************************************************************80
!
!! BESSEL_I1 evaluates the Bessel I function of order I.
!
!  Discussion:
!
!    The main computation evaluates slightly modified forms of
!    minimax approximations generated by Blair and Edwards.
!    This transportable program is patterned after the machine-dependent
!    FUNPACK packet NATSI1, but cannot match that version for efficiency
!    or accuracy.  This version uses rational functions that theoretically
!    approximate I-SUB-1(X) to at least 18 significant decimal digits.
!    The accuracy achieved depends on the arithmetic system, the compiler,
!    the intrinsic functions, and proper selection of the machine-dependent
!    constants.
!
!  Machine-dependent constants:
!
!    beta   = Radix for the floating-point system.
!    maxexp = Smallest power of beta that overflows.
!    XMAX =   Largest argument acceptable to BESI1;  Solution to
!             equation:
!               EXP(X) * (1-3/(8*X)) / SQRT(2*PI*X) = beta**maxexp
!
!
!    Approximate values for some important machines are:
!
!                            beta       maxexp    XMAX
!
!    CRAY-1        (S.P.)       2         8191    5682.810
!    Cyber 180/855
!      under NOS   (S.P.)       2         1070     745.894
!    IEEE (IBM/XT,
!      SUN, etc.)  (S.P.)       2          128      91.906
!    IEEE (IBM/XT,
!      SUN, etc.)  (D.P.)       2         1024     713.987
!    IBM 3033      (D.P.)      16           63     178.185
!    VAX           (S.P.)       2          127      91.209
!    VAX D-Format  (D.P.)       2          127      91.209
!    VAX G-Format  (D.P.)       2         1023     713.293
!
!  Licensing:
!
!    This code is distributed under the GNU LGPL license.
!
!  Modified:
!
!    27 October 2004
!
!  Author:
!
!    Original FORTRAN77 version by William Cody, Laura Stoltz.
!    FORTRAN90 version by John Burkardt.
!
!  Reference:
!
!    Blair, Edwards,
!    Chalk River Report AECL-4928,
!    Atomic Energy of Canada, Limited,
!    October, 1974.
!
!  Parameters:
!
!    Input, real (kind = 8 ) ARG, the argument.
!
!    Output, real ( kind = 8 ) BESSEL_I1, the value of the Bessel
!    I1 function.
!
*/
	      


              __m512d
	      bessel_i1_zmm8r8(const __m512d)  __attribute__((noinline))
			                       __attribute__((hot))
				               __attribute__((regcall))
				               __attribute__((aligned(32)));


	      __m512
	      bessel_i1_zmm16r4(const __m512)  __attribute__((noinline))
			                       __attribute__((hot))
				               __attribute__((regcall))
				               __attribute__((aligned(32)));


/*
!*****************************************************************************80
!
!! BETA returns the value of the Beta function.
!
!  Discussion:
!
!    The Beta function is defined as
!
!      BETA(A,B) = ( GAMMA ( A ) * GAMMA ( B ) ) / GAMMA ( A + B )
!                = Integral ( 0 <= T <= 1 ) T**(A-1) (1-T)**(B-1) dT.
!
!  Licensing:
!
!    This code is distributed under the GNU LGPL license.
!
!  Modified:
!
!    10 July 1998
!
!  Author:
!
!    John Burkardt
!
!  Parameters:
!
!    Input, real ( kind = 8 ) A, B, the parameters of the function.
!    0.0D+00 < A,
!    0.0D+00 < B.
!
!    Output, real ( kind = 8 ) BETA, the value of the function.
!
*/


              __m512d
	      beta_zmm8r8(const __m512d,
		          const __m512d)       __attribute__((noinline))
			                       __attribute__((hot))
				               __attribute__((regcall))
				               __attribute__((aligned(32)));


/*
      !*****************************************************************************80
!
!! ARCSIN_CDF evaluates the Arcsin CDF.
!
!  Licensing:
!
!    This code is distributed under the GNU LGPL license.
!
!  Modified:
!
!    20 March 2004
!
!  Author:
!
!    John Burkardt
!
!  Parameters:
!
!    Input, real ( kind = 8 ) X, the argument of the CDF.
!
!    Input, real ( kind = 8 ) A, the parameter of the CDF.
!    A must be positive.
!
!    Output, real ( kind = 8 ) CDF, the value of the CDF.
!
*/


              __m512d
	      arcsin_cdf_zmm8r8(const __m512d,
		                const __m512d) __attribute__((noinline))
			                       __attribute__((hot))
				               __attribute__((regcall))
				               __attribute__((aligned(32)));


	       __m512
	      arcsin_cdf_zmm16r4(const __m512,
		                 const __m512) __attribute__((noinline))
			                       __attribute__((hot))
				               __attribute__((regcall))
				               __attribute__((aligned(32)));


	       __m512d
	       arcsin_cdf_inv_zmm8r8(const __m512d,
		                     const __m512d)  __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));

                __m512
	       arcsin_cdf_inv_zmm16r4(const __m512,
		                     const __m512)  __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));


	      __m512d arcsin_mean_zmm8r8()           __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));


	      __m512 arcsin_mean_zmm16r4()           __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));

/*
!*****************************************************************************80
!
!! ARCSIN_PDF evaluates the Arcsin PDF.
!
!  Discussion:
!
!    The LOGISTIC EQUATION has the form:
!
!      X(N+1) = 4.0D+00 * LAMBDA * ( 1.0D+00 - X(N) ).
!
!    where 0 < LAMBDA <= 1.  This nonlinear difference equation maps
!    the unit interval into itself, and is a simple example of a system
!    exhibiting chaotic behavior.  Ulam and von Neumann studied the
!    logistic equation with LAMBDA = 1, and showed that iterates of the
!    function generated a sequence of pseudorandom numbers with
!    the Arcsin probability density function.
!
!    The derived sequence
!
!      Y(N) = ( 2 / PI ) * Arcsin ( SQRT ( X(N) ) )
!
!    is a pseudorandom sequence with the uniform probability density
!    function on [0,1].  For certain starting values, such as X(0) = 0, 0.75,
!    or 1.0D+00, the sequence degenerates into a constant sequence, and for
!    values very near these, the sequence takes a while before becoming
!    chaotic.
!
!    The formula is:
!
!      PDF(X) = 1 / ( pi * sqrt ( A^2 - X^2 ) )
!
!  Licensing:
!
!    This code is distributed under the GNU LGPL license.
!
!  Modified:
!
!    20 March 2004
!
!  Author:
!
!    John Burkardt
!
!  Reference:
!
!    Daniel Zwillinger, Stephen Kokoska,
!    CRC Standard Probability and Statistics Tables and Formulae,
!    Chapman and Hall/CRC, 2000, pages 114-115.
!
!  Parameters:
!
!    Input, real ( kind = 8 ) X, the argument of the PDF.
!    -A < X < A.
!
!    Input, real ( kind = 8 ) A, the parameter of the CDF.
!    A must be positive.
!
!    Output, real ( kind = 8 ) PDF, the value of the PDF.
!
*/


              __m512d
	      arcsin_pdf_zmm8r8(const __m512d,
		                const __m512d)       __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));


              __m512
	      arcsin_pdf_zmm16r4(const __m512,
		                 const __m512)       __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));


/*
!*****************************************************************************80
!
!! ARCSIN_VARIANCE returns the variance of the Arcsin PDF.
!
!  Licensing:
!
!    This code is distributed under the GNU LGPL license.
!
!  Modified:
!
!    20 March 2004
!
!  Author:
!
!    John Burkardt
!
!  Parameters:
!
!    Input, real ( kind = 8 ) A, the parameter of the CDF.
!    A must be positive.
!
!    Output, real ( kind = 8 ) VARIANCE, the variance of the PDF.
!		    
*/



                __m512d
		arcsin_variance_zmm8r8(const __m512d) __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));


		 __m512
		arcsin_variance_zmm16r4(const __m512) __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));


/*
!*****************************************************************************80
!
!! ARCSIN_SAMPLE samples the Arcsin PDF.
!
!  Licensing:
!
!    This code is distributed under the GNU LGPL license.
!
!  Modified:
!
!    20 March 2004
!
!  Author:
!
!    John Burkardt
!
!  Parameters:
!
!    Input, real ( kind = 8 ) A, the parameter of the CDF.
!    A must be positive.
!
!    Input/output, integer ( kind = 4 ) SEED, a seed for the random
!    number generator.
!
!    Output, real ( kind = 8 ) X, a sample of the PDF.
!
*/


              __m512d
	      arcsin_sample_zmm8r8()                 __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));


	      __m512d
	      arcsin_sample_zmm8r8(const __m512d)     __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));


/*
!*****************************************************************************80
!
!! BETA_BINOMIAL_CDF evaluates the Beta Binomial CDF.
!
!  Discussion:
!
!    A simple summing approach is used.
!
!  Licensing:
!
!    This code is distributed under the GNU LGPL license.
!
!  Modified:
!
!    07 December 1999
!
!  Author:
!
!    John Burkardt
!
!  Parameters:
!
!    Input, integer ( kind = 4 ) X, the argument of the CDF.
!
!    Input, real ( kind = 8 ) A, B, parameters of the PDF.
!    0.0D+00 < A,
!    0.0D+00 < B.
!
!    Input, integer ( kind = 4 ) C, a parameter of the PDF.
!    0 <= C.
!
!    Output, real ( kind = 8 ) CDF, the value of the CDF.
!
*/


               __m512d
	       beta_binomial_cdf_zmm8r8(const int32_t,
		                        const int32_t,
					const __m512d,
					const __m512d) __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));


/*!*****************************************************************************80
!
!! BETA_PDF evaluates the Beta PDF.
!
!  Discussion:
!
!    The formula for the PDF is:
!
!      PDF(A,B;X) = X**(A-1) * (1-X)**(B-1) / BETA(A,B).
!
!    A = B = 1 yields the Uniform distribution on [0,1].
!    A = B = 1/2 yields the Arcsin distribution.
!        B = 1 yields the power function distribution.
!    A = B -> Infinity tends to the Normal distribution.
!
!  Licensing:
!
!    This code is distributed under the GNU LGPL license.
!
!  Modified:
!
!    01 February 1999
!
!  Author:
!
!    John Burkardt
!
!  Parameters:
!
!    Input, real ( kind = 8 ) X, the argument of the PDF.
!    0.0D+00 <= X <= 1.0.
!
!    Input, real ( kind = 8 ) A, B, the parameters of the PDF.
!    0.0D+00 < A,
!    0.0D+00 < B.
!
!    Output, real ( kind = 8 ) PDF, the value of the PDF.
!*/


               __m512d
	       beta_pdf_zmm8r8(const __m512d,
		               const __m512d,
			       const __m512d)        __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));


	       __m512
	       beta_pdf_zmm16r4(const __m512,
		               const __m512,
			       const __m512)        __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));


	       __m512d
	       beta_variance_zmm8r8(const __m512d,
		                   const __m512d )   __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));


	       __m512
	       beta_variance_zmm16r4(const __m512,
		                     const __m512 )   __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));


	       
/*
!*****************************************************************************80
!
!! WEIBULL_CDF evaluates the Weibull CDF.
!
!  Licensing:
!
!    This code is distributed under the GNU LGPL license.
!
!  Modified:
!
!    12 February 1999
!
!  Author:
!
!    John Burkardt
!
!  Parameters:
!
!    Input, real ( kind = 8 ) X, the argument of the CDF.
!    A <= X.
!
!    Input, real ( kind = 8 ) A, B, C, the parameters of the PDF.
!    0.0D+00 < B,
!    0.0D+00 < C.
!
!    Output, real ( kind = 8 ) CDF, the value of the CDF.
!		    
*/


                      __m512d
		      weibull_cdf_zmm8r8(const __m512d,
		                         const __m512d,
					 const __m512d,
					 const __m512d) __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));


		      __m512
		      weibull_cdf_zmm16r4(const __m512,
		                         const __m512,
					 const __m512,
					 const __m512) __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));


		      __m512d
		      weibull_cdf_inv_zmm8r8(const __m512d,
		                             const __m512d,
					     const __m512d,
					     const __m512d) __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));


		      __m512
		      weibull_cdf_inv_zmm16r4(const __m512,
		                             const __m512,
					     const __m512,
					     const __m512) __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));


		      __m512d
		      weibull_sample_zmm8r8(const __m512d,
		                            const __m512d,
					    const __m512d,
					    const __m512d)   __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));


		      __m512
		      weibull_sample_zmm16r4(const __m512,
		                            const __m512,
					    const __m512,
					    const __m512)   __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));

/*
!*****************************************************************************80
!
!! WEIBULL_VARIANCE returns the variance of the Weibull PDF.
!
!  Licensing:
!
!    This code is distributed under the GNU LGPL license.
!
!  Modified:
!
!    16 February 1999
!
!  Author:
!
!    John Burkardt
!
!  Parameters:
!
!    Input, real ( kind = 8 ) A, B, C, the parameters of the PDF.
!    0.0D+00 < B,
!    0.0D+00 < C.
!
!    Output, real ( kind = 8 ) VARIANCE, the variance of the PDF.
!
*/



                      __m512d
                      weibull_discrete_cdf_zmm8r8(const __m512d,
		                                  const __m512d,
					          const __m512d)  __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));

		      
		      __m512
                      weibull_discrete_cdf_zmm16r4(const __m512,
		                                   const __m512,
					           const __m512)  __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));


		      __m512d
		      weibull_discrete_pdf_zmm8r8(const __m512d,
		                                  const __m512d,
					          const __m512d)  __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));


		       __m512
		      weibull_discrete_pdf_zmm16r4(const __m512,
		                                   const __m512,
					           const __m512)  __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));


/*
!*****************************************************************************80
!
!! WEIBULL_DISCRETE_CDF_INV inverts the Discrete Weibull CDF.
!
!  Licensing:
!
!    This code is distributed under the GNU LGPL license.
!
!  Modified:
!
!    19 October 2004
!
!  Author:
!
!    John Burkardt
!
!  Parameters:
!
!    Input, real ( kind = 8 ) CDF, the value of the CDF.
!    0.0D+00 <= CDF <= 1.0.
!
!    Input, real ( kind = 8 ) A, B, the parameters of the PDF.
!    0.0D+00 <= A <= 1.0D+00,
!    0.0D+00 < B.
!
!    Output, integer ( kind = 4 ) X, the corresponding argument.
*/


                      __m512d
		      weibull_discr_icdf_zmm8r8(const __m512d,
		                                const __m512d,
						const __m512d)  __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));


		      __m512
		      weibull_discr_icdf_zmm16r4(const __m512,
		                                const __m512,
						const __m512)  __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));

/*
!*****************************************************************************80
!
!! WEIBULL_DISCRETE_SAMPLE samples the discrete Weibull PDF.
!
!  Licensing:
!
!    This code is distributed under the GNU LGPL license.
!
!  Modified:
!
!    07 March 1999
!
!  Author:
!
!    John Burkardt
!
!  Parameters:
!
!    Input, real ( kind = 8 ) A, B, the parameters of the PDF.
!    0.0D+00 <= A <= 1.0D+00,
!    0.0D+00 < B.
!
!    Input/output, integer ( kind = 4 ) SEED, a seed for the random 
!    number generator.
!
!    Output, integer ( kind = 4 ) X, a sample of the PDF.
!
*/


                       __m512d
		      weibull_discr_samp_zmm8r8(   const __m512d,
		                                   const __m512d,
						   const __m512d) __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));


/*
!*****************************************************************************80
!
!! VON_MISES_CDF evaluates the von Mises CDF.
!
!  Licensing:
!
!    This code is distributed under the GNU LGPL license.
!
!  Modified:
!
!    22 September 2005
!
!  Author:
!
!    Original FORTRAN77 version by Geoffrey Hill.
!    FORTRAN90 version by John Burkardt
!
!  Reference:
!
!    Geoffrey Hill,
!    Algorithm 518,
!    Incomplete Bessel Function I0: The von Mises Distribution,
!    ACM Transactions on Mathematical Software,
!    Volume 3, Number 3, September 1977, pages 279-284.
!
!    Kanti Mardia, Peter Jupp,
!    Directional Statistics,
!    Wiley, 2000,
!    QA276.M335
!
!  Parameters:
!
!    Input, real ( kind = 8 ) X, the argument of the CDF.
!    A - PI <= X <= A + PI.
!
!    Input, real ( kind = 8 ) A, a parameter of the PDF.
!    A is the preferred direction, in radians.
!    -PI <= A <= PI.
!
!    Input, real ( kind = 8 ) B, a parameter of the PDF.
!    B measures the "concentration" of the distribution around the
!    angle A.  B = 0 corresponds to a uniform distribution
!    (no concentration).  Higher values of B cause greater concentration
!    of probability near A.
!    0.0D+00 <= B.
!
!    Output, real ( kind = 8 ) CDF, the value of the CDF.
!
*/


                      __m512d
		      von_misses_cdf_zmm8r8(const __m512d,
		                            const __m512d,
					    const __m512d) __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));


		      
		       __m512
		      von_misses_cdf_zmm16r4(const __m512,
		                            const __m512,
					    const __m512) __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
				                     __attribute__((aligned(32)));


		      
/*
   !*****************************************************************************80
!
!! VON_MISES_PDF evaluates the von Mises PDF.
!
!  Discussion:
!
!    PDF(A,B;X) = EXP ( B * COS ( X - A ) ) / ( 2 * PI * I0(B) )
!
!    where:
!
!      I0(*) is the modified Bessel function of the first
!      kind of order 0.
!
!    The von Mises distribution for points on the unit circle is
!    analogous to the normal distribution of points on a line.
!    The variable X is interpreted as a deviation from the angle A,
!    with B controlling the amount of dispersion.
!
!  Licensing:
!
!    This code is distributed under the GNU LGPL license.
!
!  Modified:
!
!    27 October 2004
!
!  Author:
!
!    John Burkardt
!
!  Reference:
!
!    Jerry Banks, editor,
!    Handbook of Simulation,
!    Engineering and Management Press Books, 1998, page 160.
!
!    Donald Best, Nicholas Fisher,
!    Efficient Simulation of the von Mises Distribution,
!    Applied Statistics,
!    Volume 28, Number 2, pages 152-157.
!
!    Merran Evans, Nicholas Hastings, Brian Peacock,
!    Statistical Distributions,
!    Wiley, 2000,
!    LC: QA273.6.E92, pages 189-191.
!
!    Kanti Mardia, Peter Jupp,
!    Directional Statistics,
!    Wiley, 2000,
!    LC: QA276.M335
!
!  Parameters:
!
!    Input, real ( kind = 8 ) X, the argument of the PDF.
!    A - PI <= X <= A + PI.
!
!    Input, real ( kind = 8 ) A, a parameter of the PDF.
!    A is the preferred direction, in radians.
!    -PI <= A <= PI.
!
!    Input, real ( kind = 8 ) B, a parameter of the PDF.
!    B measures the "concentration" of the distribution around the
!    angle A.  B = 0 corresponds to a uniform distribution
!    (no concentration).  Higher values of B cause greater concentration
!    of probability near A.
!    0.0D+00 <= B.
!
!    Output, real ( kind = 8 ) PDF, the value of the PDF.
!              
*/



                       __m512d
		      von_misses_pdf_zmm8r8(const __m512d,
		                            const __m512d,
					    const __m512d)  __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
                                                     __attribute__((aligned(32)));

		       __m512
		      von_misses_pdf_zmm16r4(const __m512,
		                            const __m512,
					    const __m512)  __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
                                                     __attribute__((aligned(32)));

/*
!*****************************************************************************80
!
!! VON_MISES_SAMPLE samples the von Mises PDF.
!
!  Licensing:
!
!    This code is distributed under the GNU LGPL license.
!
!  Modified:
!
!    07 March 1999
!
!  Author:
!
!    John Burkardt
!
!  Reference:
!
!    Donald Best, Nicholas Fisher,
!    Efficient Simulation of the von Mises Distribution,
!    Applied Statistics,
!    Volume 28, Number 2, pages 152-157.
!
!  Parameters:
!
!    Input, real ( kind = 8 ) A, a parameter of the PDF.
!    A is the preferred direction, in radians.
!    -PI <= A <= PI.
!
!    Input, real ( kind = 8 ) B, a parameter of the PDF.
!    B measures the "concentration" of the distribution around the
!    angle A.  B = 0 corresponds to a uniform distribution
!    (no concentration).  Higher values of B cause greater concentration
!    of probability near A.
!    0.0D+00 <= B.
!
!    Input/output, integer ( kind = 4 ) SEED, a seed for the random 
!    number generator.
!
!    Output, real ( kind = 8 ) X, a sample of the PDF.
	              
*/


                      __m512d
                      von_misses_sample_zmm8r8(const __m512d,
		                               const __m512d)  __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
                                                     __attribute__((aligned(32)));


		      
                       __m512
                      von_misses_sample_zmm16r4(const __m512,
		                                const __m512)  __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
                                                     __attribute__((aligned(32)));


/*
!*****************************************************************************80
!
!! RAYLEIGH_PDF evaluates the Rayleigh PDF.
!
!  Discussion:
!
!    PDF(A;X) = ( X / A^2 ) * EXP ( - X^2 / ( 2 * A^2 ) )
!
!  Licensing:
!
!    This code is distributed under the GNU LGPL license.
!
!  Modified:
!
!    15 February 1999
!
!  Author:
!
!    John Burkardt
!
!  Parameters:
!
!    Input, real ( kind = 8 ) X, the argument of the PDF.
!    0.0D+00 <= X
!
!    Input, real ( kind = 8 ) A, the parameter of the PDF.
!    0 < A.
!
!    Output, real ( kind = 8 ) PDF, the value of the PDF.
                      
*/


                       __m512d
		      rayleigh_pdf_zmm8r8(const __m512d,
		                          const __m512d) __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
                                                     __attribute__((aligned(32)));


		       __m512
		      rayleigh_pdf_zmm16r4(const __m512,
		                          const __m512) __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
                                                     __attribute__((aligned(32)));


/*
!*****************************************************************************80
!
!! RAYLEIGH_MEAN returns the mean of the Rayleigh PDF.
!
!  Licensing:
!
!    This code is distributed under the GNU LGPL license.
!
!  Modified:
!
!    16 February 1999
!
!  Author:
!
!    John Burkardt
!
!  Parameters:
!
!    Input, real ( kind = 8 ) A, the parameter of the PDF.
!    0.0D+00 < A.
!
!    Output, real ( kind = 8 ) MEAN, the mean of the PDF.		     
*/


                       __m512d
		      rayleigh_mean_zmm8r8(const __m512d)__attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
                                                     __attribute__((aligned(32)));


						     
                        __m512
		      rayleigh_mean_zmm16r4(const __m512)__attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
                                                     __attribute__((aligned(32)));


/*
!*****************************************************************************80
!
!! RAYLEIGH_CDF_INV inverts the Rayleigh CDF.
!
!  Licensing:
!
!    This code is distributed under the GNU LGPL license.
!
!  Modified:
!
!    16 February 1999
!
!  Author:
!
!    John Burkardt
!
!  Parameters:
!
!    Input, real ( kind = 8 ) CDF, the value of the CDF.
!    0.0D+00 <= CDF <= 1.0.
!
!    Input, real ( kind = 8 ) A, the parameter of the PDF.
!    0.0D+00 < A.
!
!    Output, real ( kind = 8 ) X, the corresponding argument.
*/


                      __m512d
		      rayleigh_invcdf_zmm8r8(const __m512d,
		                             const __m512d) __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
                                                     __attribute__((aligned(32)));


		      
		       __m512
		      rayleigh_invcdf_zmm16r4(const __m512,
		                             const __m512) __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
                                                     __attribute__((aligned(32)));
/*
!*****************************************************************************80
!
!! RAYLEIGH_CDF evaluates the Rayleigh CDF.
!
!  Licensing:
!
!    This code is distributed under the GNU LGPL license.
!
!  Modified:
!
!    16 February 1999
!
!  Author:
!
!    John Burkardt
!
!  Parameters:
!
!    Input, real ( kind = 8 ) X, the argument of the CDF.
!    0.0D+00 <= X.
!
!    Input, real ( kind = 8 ) A, the parameter of the PDF.
!    0.0D+00 < A.
!
!    Output, real ( kind = 8 ) CDF, the value of the CDF.
*/



                      __m512d
		      rayleigh_cdf_zmm8r8(const __m512d,
		                          const __m512d) __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
                                                     __attribute__((aligned(32)));


		       __m512
		      rayleigh_cdf_zmm16r4(const __m512,
		                          const __m512) __attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
                                                     __attribute__((aligned(32)));



		      __m512d
		      rayleigh_sample_zmm8r8(const __m512d,
		                             const __m512d)__attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
                                                     __attribute__((aligned(32)));


		      __m512
		      rayleigh_sample_zmm16r4(const __m512,
		                             const __m512)__attribute__((noinline))
			                             __attribute__((hot))
				                     __attribute__((regcall))
                                                     __attribute__((aligned(32)));


		      












#endif /*__GMS_CDF_PDF_AVX512_H__*/
